### ISSUE TITLE
`dlsym` finds the wrong symbol from another handle

### ISSUE THREAD

**Issue by Fernthedev** [sc2ad/scotland2#11]
It seems that if a `extern "C"` function does not hide its visibility, it may be used to resolve the symbol in later usages of `dlsym` with a distinct handle even though `dlopen` uses `RTLD_LOCAL`. This would imply the symbol is re-exported just through linking a dependency, though this still remains unclear.

Situation: mod `A` depends on mod `B` and both are late mods. If mod `A` does not have `late_load`, it will use mod `B`'s `late_load` and cause a double call. This should instead be `null`

Discord discussion https://discord.com/channels/994470435100033074/1011387411021975564/1201031750604824587

**Comment by Fernthedev** [comment]
Should be resolved with this https://github.com/sc2ad/scotland2/pull/12

**Comment by sc2ad** [comment]
Resolved in #12
